---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://3.35.107.8:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUBuHh5vKSTuF0Na48AQctr5MHpccwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMDI1MDQ0MTAwWhcNMzUxMDIyMDQ0MTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABE1G
          mDHOPynMODk1hslQJH09iBlliH751CVI+gpg/exKyQk0dAc8RuotX7gpYPs+mQPc
          NXc34DdmxdHmC85J35ajRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTBFhRXNgQ06tRPPhf3dBRBjKCsTDAKBggqhkjOPQQD
          AgNHADBEAiA1qs7JBCBnpnrJKopPnd/BS/HZbAMwIseLW2/b3YPFJgIger1E1d06
          vSCnjcg4NWwpxgXNTaPFsooFKA/OtPx+Y3U=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://3.35.107.8:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUBuHh5vKSTuF0Na48AQctr5MHpccwCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAxMDI1MDQ0MTAwWhcNMzUxMDIyMDQ0MTAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABE1G
          mDHOPynMODk1hslQJH09iBlliH751CVI+gpg/exKyQk0dAc8RuotX7gpYPs+mQPc
          NXc34DdmxdHmC85J35ajRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBTBFhRXNgQ06tRPPhf3dBRBjKCsTDAKBggqhkjOPQQD
          AgNHADBEAiA1qs7JBCBnpnrJKopPnd/BS/HZbAMwIseLW2/b3YPFJgIger1E1d06
          vSCnjcg4NWwpxgXNTaPFsooFKA/OtPx+Y3U=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
